### ISSUE TITLE
KNN code

### ISSUE THREAD

**Issue by Leedia-exe** [nikitaa30/Recommender-Systems#1]
Hey nikita, your course was very helpful thank you!
i was wondering if you could send me the code (not in the jupiter format) 
and to ask if it is possible to aply recall and precision metrics in this algorithm
Thanks again

**Comment by nikitaa30** [comment]
the .py version is right there in the same directory by the name 'knn recommender.py'.
 Also, recall and precision are possible for this algorithm, when your code predicts the rating of the recommended item and compare that with actual or test data.

**Comment by Leedia-exe** [comment]
Thanks a lot!
Have a good day

Le mer. 13 mai 2020 à 17:03, Nikita Sharma <notifications@github.com> a
écrit :

**Comment by Leedia-exe** [comment]
Can you give me a quick tip of how can i do it?

Le mer. 13 mai 2020 à 17:03, Nikita Sharma <notifications@github.com> a
écrit :

**Comment by nikitaa30** [comment]
sure, just found some quick links for you~ If you come across any issue, please let me know
https://medium.com/@m_n_malaeb/recall-and-precision-at-k-for-recommender-systems-618483226c54

https://www.researchgate.net/figure/Precision-and-recall-of-recommendations-of-recommender-systems_tbl4_324481236

**Comment by Leedia-exe** [comment]
Amazing!
Thank you

Le mer. 13 mai 2020 à 18:04, Nikita Sharma <notifications@github.com> a
écrit :

**Comment by Leedia-exe** [comment]
hello,
Sorry for all these questions, but in your knn algorithm we predicted the
movies not the ratings, how can we apply recall/ precision then ?
Thanks a lot

Le mer. 13 mai 2020 à 17:04, lydia younsi <younsilydia23@gmail.com> a
écrit :

**Comment by nikitaa30** [comment]
Mine is a content based knn, you should adapt a collaborative approach which outputs ratings, then you can compare those ratings.

**Comment by Leedia-exe** [comment]
Can you help me do it?

Le ven. 15 mai 2020 à 11:22, Nikita Sharma <notifications@github.com> a
écrit :
